export const AppContent = {
  liked: "You have already liked the post!",
  dislike: "You have already dis-liked the post!",
  saveText: "Save",
  updateText: "Update",
  deleteText: "Delete",
  signIn: "Sign In",
  signUp: "Sign Up",
  signUpHere: "sign up here",
  signInHere: "sign in here",
  signupText: "Don't have an account? click here to",
  signInText: "Already have an account?",
  createPost: "Create Post",
  publish: "Publish",
  fileUploadDragText: "Drag files to upload",
  browse: "Browse",
  or: "Or",
};
